/* eslint-disable import/prefer-default-export */
export enum SEARCH_ADDRESS_STATE {
    INITIAL= 'INITIAL',
    ADDRESSES_FOUND ='ADDRESSES_FOUND',
    ADDRESS_NOT_FOUND='ADDRESS_NOT_FOUND',
    SELECTED_ADDRESS='SELECTED_ADDRESS',
}
